### ISSUE TITLE
一个问题

### ISSUE THREAD

**Issue by pyni** [go2sea/DQfD#2]
go2sea．你好！
看到你的代码获益良多！
有两个问题想咨询一下：
一个是我看原文中有N-step TD losses，是不是代码中没有？
另一个是想问一下监督loss的作用到底是什么（因为我感觉把监督loss去掉，效果好像也还行）．．．

**Comment by go2sea** [comment]
你好！在我发布这个代码之后论文有更新，我实现时的那个版本中是没有n-step td losses的。
我没有做过有无监督loss的对比，暂时无法回答你第二个问题。但我觉得demo data作为高质量的训练数据，应该被保留。

**Comment by pyni** [comment]
多谢回复！
