### ISSUE TITLE
Some questions about n-step loss and supervised loss 

### ISSUE THREAD

**Issue by Sophistt** [go2sea/DQfD#3]
Hi, go2sea! What a great job it is!  But I have some questions about your code. I find that in the paper, the total loss includes the n-step double Q-learning loss, but it seems is not in your code. What's more, does the supervised loss make a difference in training network?

**Comment by go2sea** [comment]
The paper was updated after my implementation, and there is no n-step loss in the previous version. Maybe I will update my code later.
I don't have any evidence that supervised loss make big positive difference, but I think the demo data should be involved as high quality trainning data.

**Comment by Sophistt** [comment]
Thanks a lot! I will close the issue.
